export default {
  formError: {
    nameRequired: 'Full name is required.',
    nameMin: 'Full name should be atleast 3 characters.',
    usernameRequired: 'Username is required.',
    usernameMin: 'Username should be atleast 3 characters.',
    usernameNoSpace: "Username can't have space.",
    phoneRequired: 'Phone number is required.',
    phoneMin: 'Phone number should be atleast 6 characters.',
    phoneMax: "Phone number can't be more than 15 characters.",
    storeNameRequired: 'Store name is required.',
    emailRequired: 'Email address is required.',
    emailInvalid: 'Enter a valid email address.',
    passwordRequired: 'Password is required.',
    passwordMin: 'Password should be atleast 8 characters.',
  },
  SignUpMessage: 'Successfully created your account.',
  passwordChangeMessage: 'Successfully changed your password.',
  forgotPassword: 'Forgot Password?',
  EMAIL_PASSWORD_EMPTY: 'Please enter your email and password.',
  INVALID_EMAIL: 'Please provide a valid email address.',
  Exit: 'Exit',
  ExitConfirm: 'Are you sure you want to exit this app',
  YES: 'YES',
  OK: 'OK',
  ViewMyOrders: 'View My Oders',
  CANCEL: 'CANCEL',
  Confirm: 'Confirm',

  // Scene's Titles
  Home: 'Home',
  Intro: 'Intro',
  Product: 'Product',
  Cart: 'Cart',
  WishList: 'WishList',
  InputPhone: 'Please input your phone',

  // Home
  products: 'products',

  // TopBar
  ShowFilter: 'Sub Categories',
  HideFilter: 'Hide',
  Sort: 'Sort',
  textFilter: 'Recent',

  // Category
  ThereIsNoMore: 'There is no more product to show',

  // Product
  AddedtoCart: 'Added item to Cart',
  AddtoCart: 'Add to Cart',
  AddtoWishlist: 'Add to Wishlist',
  ProductVariations: 'Variations',
  NoVariation: "This product don't have any variation",
  AdditionalInformation: 'Description',
  NoProductDescription: 'No Product Description',
  ProductReviews: 'Reviews',
  NoReview: "This product don't have any reviews ...yet",
  BUYNOW: 'BUY NOW',
  ProductLimitWaring: "You can't add more than 10 product",
  EmptyProductAttribute: "This product don't have any attributes",
  ProductFeatures: 'Features',
  ErrorMessageRequest: "Can't get data from server",
  NoConnection: 'No internet connection',
  ProductRelated: 'You May Also Like',

  // Cart
  NoCartItem: 'There is no product in cart',
  Total: 'Total',
  EmptyCheckout: "Sorry, you can't check out an empty cart",
  RemoveCartItemConfirm: 'Remove this product from cart?',
  MyCart: 'Cart',
  Order: 'Order',
  ShoppingCart: 'Shopping Cart',
  ShoppingCartIsEmpty: 'Your Cart is Empty',
  Delivery: 'Delivery',
  AddProductToCart: 'Add a product to the shopping cart',
  TotalPrice: 'Total Price:',
  YourDeliveryInfo: 'Your delivery info:',
  ShopNow: 'Shop Now',
  YourChoice: 'Your wishlist:',
  YourSale: 'Your Sale:',
  SubtotalPrice: 'Subtotal Price:',
  BuyNow: 'Buy Now',
  Items: 'items',
  Item: 'item',
  ThankYou: 'Thank you',
  FinishOrderCOD: 'You can use to number of order to track shipping status',
  FinishOrder:
    'Thank you so much for your purchased, to check your delivery status please go to My Orders',
  NextStep: 'Next Step',
  ConfirmOrder: 'Confirm Order',
  RequireEnterAllFileds: 'Please enter all fields',
  Error: 'Error',
  InvalidEmail: 'Invalid email address',
  Finish: 'Finish',

  // Wishlist
  NoWishListItem: 'There is no item in wishlist',
  MoveAllToCart: 'Add all to cart',
  EmptyWishList: 'Empty wishlist',
  EmptyAddToCart: 'Sorry, the wishlist is empty',
  RemoveWishListItemConfirm: 'Remove this product from wishlist?',
  CleanAll: 'Clean All',

  // Sidemenu
  SignIn: 'Log In',
  SignOut: 'Log Out',
  GuestAccount: 'Guest Account',
  CantReactEmailError:
    "We can't reach your email address, please try other login method",
  NoEmailError: "Your account don't have valid email address",
  EmailIsNotVerifiedError:
    "Your email address is not verified, we can' trust you",
  Shop: 'Shop',
  News: 'News',
  Contact: 'Contact us',
  Setting: 'Setting',
  Login: 'Login',
  Logout: 'Logout',
  Category: 'Category',

  // Checkout
  Checkout: 'Checkout',
  ProceedPayment: 'Proceed Payment',
  Purchase: 'Purchase',
  CashOnDelivery: 'Cash on Delivery',
  Paypal: 'Paypal',
  Stripe: 'Stripe',
  CreditCard: 'Credit Card',
  PaymentMethod: 'Payment Method - Not select',
  PaymentMethodError: 'Please select your payment method',
  PayWithCoD: 'Your purchase will be pay when goods were delivered',
  PayWithPayPal: 'Your purchase will be pay with PayPal',
  PayWithStripe: 'Your purchase will be pay with Stripe',
  ApplyCoupon: 'Apply',
  CouponPlaceholder: 'COUPON CODE',
  APPLY: 'APPLY',
  Back: 'Back',
  CardNamePlaceholder: 'Name written on card',
  BackToHome: 'Back to Home',
  OrderCompleted: 'Your order was completed',
  OrderCanceled: 'Your order was canceled',
  OrderFailed: 'Something went wrong...',
  OrderCompletedDesc: 'Your order id is ',
  OrderCanceledDesc:
    'You have canceled the order. The transaction has not been completed',
  OrderFailedDesc:
    'We have encountered an error while processing your order. The transaction has not been completed. Please try again',
  OrderTip:
    'Tip: You could track your order status in "My Orders" section from side menu',
  Payment: 'Payment',
  Complete: 'Complete',
  EnterYourFirstName: 'Enter your First Name',
  EnterYourLastName: 'Enter your Last Name',
  EnterYourEmail: 'Enter your email',
  EnterYourPhone: 'Enter your phone',
  EnterYourAddress: 'Enter your address',
  CreateOrderError: 'Cannot create new order. Please try again later',
  AccountNumner: 'Account number',
  CardHolderName: 'Cardholder Name',
  ExpirationDate: 'Expiration Date',
  SecurityCode: 'CVV',

  // myorder
  OrderId: 'Order ID',
  MyOrder: 'My Orders',
  NoOrder: "You don't have any orders",
  OrderDate: 'Order Date: ',
  OrderStatus: 'Status: ',
  OrderPayment: 'Payment method: ',
  OrderTotal: 'Total: ',
  OrderDetails: 'Show detail',
  ShippingAddress: 'Shipping Address:',
  Refund: 'Refund',

  PostDetails: 'Post Details',
  FeatureArticles: 'Feature articles',
  MostViews: 'Most views',
  EditorChoice: 'Editor choice',

  // settings
  Settings: 'Settings',
  BASICSETTINGS: 'BASIC SETTINGS',
  Language: 'Language',
  INFO: 'INFO',
  About: 'About us',
  changeRTL: 'Switch RTL',

  // language
  AvailableLanguages: 'Available Languages',
  SwitchLanguage: 'Switch Language',
  SwitchLanguageConfirm: 'Switch language require an app reload, continue?',
  SwitchRtlConfirm: 'Switch RTL require an app reload, continue?',

  // about us
  AppName: 'MSTORE',
  AppDescription: 'React Native template for mCommerce',
  AppContact: ' Contact us at: mstore.io',
  AppEmail: ' Email: support@mstore.io',
  AppCopyRights: '© MSTORE 2016',

  // contact us
  contactus: 'Contact us',

  // form
  NotSelected: 'Not selected',
  EmptyError: 'This field is empty',
  DeliveryInfo: 'Delivery Info',
  FirstName: 'First Name',
  LastName: 'Last Name',
  Address: 'Address',
  City: 'Town/City',
  State: 'State',
  NotSelectedError: 'Please choose one',
  Postcode: 'Postcode',
  Country: 'Country',
  Email: 'Email',
  Phone: 'Phone Number',
  Note: 'Note',

  // search
  Search: 'Search',
  SearchPlaceHolder: 'Search product by name',
  NoResultError: 'Your search keyword did not match any products.',
  Details: 'Details',

  // filter panel
  Categories: 'Categories',

  // sign up
  profileDetail: 'Profile Details',
  firstName: 'First name',
  lastName: 'Last name',
  accountDetails: 'Account Details',
  username: 'Username',
  email: 'Email',
  generatePass: 'Use generate password',
  password: 'Password',
  signup: 'Sign Up',

  // filter panel
  Loading: 'LOADING...',
  welcomeBack: 'Welcome back! ',
  seeAll: 'Show All',

  // Layout
  cardView: 'Card ',
  simpleView: 'List View',
  twoColumnView: 'Two Column ',
  threeColumnView: 'Three Column ',
  listView: 'List View',
  default: 'Default',
  advanceView: 'Advance ',
  horizontal: 'Horizontal ',

  couponCodeIsExpired: 'This coupon code is expired',
  invalidCouponCode: 'This coupon code is invalid',
  remove: 'Remove',
  reload: 'Reload',
  applyCouponSuccess: 'Congratulations! Coupon code applied successfully ',
  applyCouponFailMin: `This minimum spend for this coupon is `,
  applyCouponFailMax: `This maximum spend for this coupon is `,

  OutOfStock: 'OUT OF STOCK',
  ShippingType: 'Shipping method',

  // Place holder
  TypeFirstName: 'Type your first name',
  TypeLastName: 'Type your last name',
  TypeAddress: 'Type address',
  TypeCity: 'Type your town or city',
  TypeState: 'Type your state',
  TypeNotSelectedError: 'Please choose one',
  TypePostcode: 'Type postcode',
  TypeEmail: 'Type email (Ex. acb@gmail.com), ',
  TypePhone: 'Type your phone number',
  TypeNote: 'Note',
  TypeCountry: 'Select country',
  SelectPayment: 'Select Payment method',
  close: 'CLOSE',
  noConnection: 'NO INTERNET ACCESS',

  // user profile screen
  AccountInformations: 'Account Informations',
  PushNotification: 'Push notification',
  DarkTheme: 'Dark Theme',
  Privacy: 'Privacy policies',
  SelectCurrency: 'Select currency',
  Name: 'Name',
  Currency: 'Currency',
  Languages: 'Languages',

  GetDataError: "Can't get data from server",
  UserOrEmail: 'Username or email',
  Or: 'Or',
  FacebookLogin: 'Facebook Login',
  DontHaveAccount: "Don't have an account?",

  // Horizontal
  featureProducts: 'Feature Products',
  bagsCollections: 'Bags Collections',
  womanBestSeller: 'Woman Best Seller',
  manCollections: 'Man Collections',

  // Modal
  Select: 'Select',
  Cancel: 'Cancel',
  Guest: 'Guest',

  LanguageName: 'English',

  // review
  vendorTitle: 'Vendor',
  comment: 'Leave a review',
  yourcomment: 'Your comment',
  placeComment:
    'Tell something about your experience or leave a tip for others',
  writeReview: 'Review',
  thanksForReview:
    'Thanks for the review, your content will be verify by the admin and will be published later',
  errInputComment: 'Please input your content to submit',
  errRatingComment: 'Please rating to submit',
  send: 'Send',

  termCondition: 'Term & Condition',
  Subtotal: 'Subtotal',
  Discount: 'Discount',
  Shipping: 'Shipping',
  Taxes: 'Taxes',
  Recents: 'Recents',
  Filters: 'Filters',
  Princing: 'Pricing',
  Filter: 'Filter',
  ClearFilter: 'Clear Filter',
  ProductCatalog: 'Product Catalog',
  ProductTags: 'Product Tags',
  AddToAddress: 'Add to Address',
  SMSLogin: 'SMS Login',
  OrderNotes: 'Order Notes',

  CanNotLogin: 'Can not login, something was wrong!',
  PleaseCompleteForm: 'Please complete the form!',
  ServerNotResponse: "Server doesn't response correctly",
  CanNotRegister: "Can't register user, please try again.",
};
